### ISSUE TITLE
 Unable to locate a class or view for component [form-input]. 

### ISSUE THREAD

**Issue by underdpt** [hostmoz/blade-bootstrap-components#1]
Hi,

Just trying your package. After installation on a fresh Laravel 8 and setting some random inputs, it throws the exception:

```
InvalidArgumentException
Unable to locate a class or view for component [form-input]. 
```

**Comment by backstageel** [comment]
The correct syntax should be: 
`<x-bootstrap::form.input name="description" label="Description" />`

note the dot between form and input. I will update the docs
